### ISSUE TITLE
Conflicting package versions in requirements.txt

### ISSUE THREAD

**Issue by GingerYouth** [anonymousgn1/Minecraft#10]
Hi, your _requirements.txt_ has conflicting package versions:
```
The conflict is caused by:
    The user requested gitpython==3.1.41
    pydriller 2.5 depends on gitpython==3.1.30
```

**Comment by saikrishna4276** [comment]
Hi, thank you for letting me know about this issue. I downgraded the version of GitPython to 3.1.30 in [requirements.txt](https://github.com/SET-IITGN/Minecraft/blob/main/requirements.txt)
